### ISSUE TITLE
自動戰鬥結束後，點擊關閉結算視窗的位置

### ISSUE THREAD

**Issue by a062670** [josh-hsu/CrossAuto#21]
戰鬥結束後會點一下關閉結算視窗，點的位置偏下了，所以逃跑的時候或是PK結束的時候，會往下走一步

試試看 311, 227，偏移 25, 15

**Comment by josh-hsu** [comment]
Fixed in v21.7.06.01 Release
1. 新增圖檔辣椒、米、白金條以及赤松 
2. 修正戰鬥後結算視窗點擊位置
3. 可能可以修正關掉工具後，但工具還在動的問題
