### ISSUE TITLE
辣椒跟米

### ISSUE THREAD

**Issue by a062670** [josh-hsu/CrossAuto#22]
[item.zip](https://github.com/josh-hsu/CrossAuto/files/6765209/item.zip)

**Comment by josh-hsu** [comment]
Fixed in v21.7.06.01 Release
1. 新增圖檔辣椒、米、白金條以及赤松 
2. 修正戰鬥後結算視窗點擊位置
3. 可能可以修正關掉工具後，但工具還在動的問題
